#!/usr/bin/env python3
"""Stub for staticnested attack tool"""

import sys

print(
    "ERROR: 'staticnested' binary not found! Please compile from source or download pre-built binaries."
)
sys.exit(1)
